### ISSUE TITLE
Filter mob memories to only remember certain bosses

### ISSUE THREAD

**Issue by janhkrueger** [adrianocastro189/memory#104]
Thanks for your addon! While I still trying to figure out how to utilise it fully, following questions came up to me.

Currently the addOn remembers all mobs, irrelevant and bosses.

Is it possible to let only boss kills be remembered?

Or filter out for example that "regular orc grunt" even gets added? With the ability to remove all already saved entries from "regular orc grunt".

**Comment by adrianocastro189** [comment]
Hi, Jan.

First of all, thank you for your comment and your suggestion. I appreciate all the feedback I receive from players and try my best to find a solution for them all.

The way Memory is implemented, it doesn't have a way to filter out enemy types. However, it's in my backlog to create a settings frame to replace the current slash commands. Along with those, I'm working on selecting which settings are a good improvement for the addon.

I have already a version planned for the next days which should have the development started this week or next, so I'm afraid I can't study your suggestion now, but I can guarantee it will be prioritized for the version after the next one. I'll reply to this issue as soon as I have answers for you and an estimated date to release if that's doable to include now or if it will require more refactoring.

Thanks again!

**Comment by janhkrueger** [comment]
Hey, thanks for your answer!

And no problem, was just an idea. No need to priorize it for me. I'm also still exploring the potential for myself. And propably start to using /memoryaddon addm  more ;)

But a new version sounds good and be happy to update when it ships.

**Comment by adrianocastro189** [comment]
Hi, Jan.

Coming back to this thread to let you know that, unfortunately, this can't be simply implemented given how Memory registers mob counts from the combat log. From an initial research, I couldn't find a way to determine whether a creature is a boss or not programatically -- Probably there's a way, but not trivial, especially for Classic versions.

I could come up with a list of boss names but that would require constant updates whenever new raids or dungeons come up as well as map localized names for players using other idioms in their clients.

The thing is, Memory was designed to be a simple addon registering all kinds of arbitrary memories during gameplay and I'm also afraid that opening the possibility to filter types of enemies could result in another purpose for the addon. I hope you understand this is a design decision that I wouldn't want to change by now.

Not sure if you use [DBM](https://www.curseforge.com/wow/addons/deadly-boss-mods) but it actually have counters for all dungeon and raid bosses kills and that may provide you the data you're looking for.

Again, I really appreciate your feedback and hope you share other ideas you may have.

**Comment by janhkrueger** [comment]
No problem!

Was just an idea.
