### ISSUE TITLE
How to get rid of debug messages?

### ISSUE THREAD

**Issue by tflo** [adrianocastro189/memory#64]
How can I get rid of these debug messages, like

```
<Memory Debug>  loot memory stored for items
<Memory Debug>  talk memory stored for npcs
…
```

Unfortunatly `/memoryaddon help` doesn’t return anything.

TIA

– Tom

**Comment by tflo** [comment]
OK, seems I found the problem:

CurseBreaker does not see any versions after 0.6.0-beta from december, so I was playing with 0.6.0 all the time, instead of 1.1.1.
(0.6.0 has a line that force-enables debug messages.)

I’ve seen something similar already with another addon recently. I contacted the author and she found out that curseforge failed to publish the latest files. The reason was unknown, but a fresh upload made the file available again. ([See this](https://github.com/trozware/ZonePet/issues/1).)

Maybe you want to check that also, because I’m probably not the only one who is/was using an old file because of that.

– Tom

**Comment by adrianocastro189** [comment]
Hi @tflo! Thanks for posting this issue here! I'll contact CurseForge to see why the current releases are not being published. I've testes with the CurseForge application and it looks updated, but there's probably an issue to broadcast to other apps.

By the way, are you using the addon on Classic/BC or Retail? It's been a while since I don't test it on Retail.

Thank you again!

**Comment by tflo** [comment]
I’m using it with Retail.

Let me know what you find out about the curseforge listing/broadcasting issue. Maybe you want to contact the ZonePet author (see link above), to find out if she knows more about the issue. IIRC and AFAIK, the publishing was fixed after she re-uploaded the latest file _with a new version number_ (without changing anything else). 

But the symptoms were slightly different: with ZonePet _all_ releases stopped being broadcasted (CurseBreaker suddenly could not find any), whereas with your addon at least the 0.6.0 version is broadcasted.

**Comment by adrianocastro189** [comment]
@tflo not forgetting about this ticket, mate. Opened a ticket with CurseForge and still waiting for their response.

Appreciate your patience.

**Comment by adrianocastro189** [comment]
@tflo I finally got why you're not seeing that version on CurseBreaker. You mentioned that you use this addon on Retail, right? When the first release after the addon was published, I've removed Retail as a supported version as I don't test it on it, but only in Classic.

It probably works as it doesn't make use of specific API calls, but since I don't do the proper tests, I can't add the retail version as a supported version, and that's why CurseBreaker gets the most recent as the 0.6.0. I'm afraid that you'd have to download it and replace it in your addons folder manually.

Thank you for posting this issue.

```
Type | Name | Size | Uploaded | Game Version | Downloads | Status | &nbsp; | Actions
-- | -- | -- | -- | -- | -- | -- | -- | --
R | memory-1.1.1.zip | 41.07 KB | May 16, 2021 | 1.13.7 | 51 | Approved | &nbsp; | &nbsp;
R | memory-1.1.0.zip | 40.39 KB | Mar 20, 2021 | 1.13.6 | 38 | Approved | &nbsp; | &nbsp;
R | memory-1.0.0.zip | 35.85 KB | Jan 19, 2021 | 1.13.6 | 38 | Approved | &nbsp; | &nbsp;
----------
B | memory-0.6.0-beta.zip | 32.14 KB | Dec 12, 2020 | 1.13.6                             +1 | 120 | Approved | &nbsp; | &nbsp;
B | memory-0.5.0-beta.zip | 26.31 KB | Nov 25, 2020 | 9.0.2                             +1 | 19 | Approved | &nbsp; | &nbsp;
A | memory-0.4.0-alpha.zip | 24.12 KB | Nov 20, 2020 | 9.0.2                             +1 | 6 | Approved | &nbsp; | &nbsp;
A | memory-0.3.0-alpha.zip | 16.65 KB | Oct 23, 2020 | 9.0.1                             +1 | 10 | Approved | &nbsp; | &nbsp;
A | memory-0.2.0-alpha.zip | 15.53 KB | Oct 18, 2020 | 9.0.1                             +1 | 10 | Approved | &nbsp; | &nbsp;
A | memory-0.1.0-alpha.zip | 13.48 KB | Oct 15, 2020 | 1.13.5                             +1 | 9 | Approved | &nbsp; | &nbsp;
```

**Comment by tflo** [comment]
> When the first release after the addon was published, I've removed Retail as a supported version […]

Okay, then it was not curseforge’s fault. This time ;)

> It probably works as it doesn't make use of specific API calls, but since I don't do the proper tests, I can't add the retail version as a supported version […]. I'm afraid that you'd have to download it and replace it in your addons folder manually.

That’s what I’ve done at the time of my second post (12 days ago). And I haven’t experienced any issues, so far. (Using it on ~10 active toons, all on Retail.)

So, IMHO, you could easily list the current version for Retail. Maybe just add a note to the description on curseforge that you only actively support the addon for Classic. (That way people know that they might have to fix the addon themselves, if issues come up with Retail.)

Many thanks for your efforts. And for the addon, of course!

PS:

I just checked the curseforge Files page again, and 1.1.1 is clearly labeled as “Classic” there. I could have actually seen that two weeks ago if I had looked properly ;)

**Comment by adrianocastro189** [comment]
> So, IMHO, you could easily list the current version for Retail. Maybe just add a note to the description on curseforge that you only actively support the addon for Classic. (That way people know that they might have to fix the addon themselves, if issues come up with Retail.)

@tflo Yeah, you're right. That would be better rather than restricting it to Classic/TBC. Thank you very much for your suggestion!

I'm about to publish a new `1.2.0` release soon with a new feature and will use the same release to add the note + the supported retail version so you should be able to update it with CurseBreaker. Please, let me know if you still have issues with that.

I'm planning to do that release until the next Sunday.

**Comment by tflo** [comment]
That’s great to hear! (I hate it when I have to manually babysit my add-on versions ;)

Once the 1.2.0 is live I’ll report back if it’s seen by CurseBreaker and if the new feature works with Retail.

Thanks.

**Comment by adrianocastro189** [comment]
Hi @tflo ! Release 1.2.0 is deployed and the Retail's version is also set up, which means you should be able to update it via CurseBreaker (maybe it can take some time for the app to show this version).

I also left a thank you for you in the Changelog's entry for the suggestion!

Hope you can update it and enjoy the new feature introduced on 1.2.0. 👋

**Comment by tflo** [comment]
I see the 1.2.0 on the Files page on curseforge, but CurseBreaker still lists 0.6.0 as latest version (set to Retail). I also checked with WoWUp and Ajour (these are programs similar to CurseBreaker), and they also see only 0.6.0. I repeatedly refreshed the listing of all the programs, of course.

I also checked if it maybe got registered as a separate add-on by searching for new (not installed) add-ons with the string “memory”. But nope.

Weird. Maybe we have to wait a couple of days? Well, if doesn’t appear tomorrow, I’ll download it manually.

Thanks again.
Take care
– Tom

**Comment by tflo** [comment]
CurseBreaker and friends still insist that 0.6.0 is the latest version for Retail. 

Well, I installed 1.2.0 now with  the `-i` switch (‘ignore client version’), which obviously works, by force.

Weird though.

The add-on itself (1.2.0) seems to continue to work fine with Retail. Haven’t done too much testing though, and also haven’t yet tried the new screenshot feature.

**Comment by adrianocastro189** [comment]
@tflo Thank you very much for the feedback.

It's so weird... I updated the `.toc` file with the current Retail interface version and set those as well for the uploaded files on CurseForge. 🤔

But I'm glad you are able to update it with the `-i` option.

Hope you enjoy the new version! Cheers!
