### ISSUE TITLE
Tooltip toggle

### ISSUE THREAD

**Issue by oddtoddy** [adrianocastro189/memory#74]
Love the addon! Would it be possible to add a toggle to disable the tooltip text? Such as:
Fight                   x1
First                   January 8, 2022
Last                   January 8, 2022

Sometimes it clutters up the tooltip when using other addons.

**Comment by adrianocastro189** [comment]
@oddtoddy First of all, apologies for taking more than 2 years to provide you a reply!

I was out of World of Warcraft addons development for a while and got no notifications for this issue you opened.

Now that I'm retaking the work in the Memory addon, I'll be happy to add a setting to allow players disabling tooltip text.

Thank you very much for posting it and, again, sorry for the huge delay.

**Comment by adrianocastro189** [comment]
Now it's possible to disable memories added to tooltips by running `/memoryaddon set memory.showInTooltips 0` in [version 1.2.4](https://www.curseforge.com/wow/addons/memory).

Thanks again for the suggestion.
